baseURL = 'https://gui13go.github.io/'
languageCode = 'en-us'
title = 'Gui13go'
theme = 'PaperMod'

enableEmoji = true

[pagination]
  pagerSize = 1000

[params]
  env = 'production'
  title = 'Gui13go'
  description = 'Personal technical blog on GNU/Linux, Systems Engineering, Security, Virtualization, and Cloud Architecture.'
  keywords = ['Blog', 'Linux', 'Security', 'Kubernetes', 'Cloud', 'DevOps', 'Systems']
  author = 'Guilherme Viegas'

  [params.label]
    text = 'Gui13go'

  [params.profileMode]
    enabled = true
    title = 'Guilherme Viegas'
    subtitle = 'Systems Engineer & Researcher'

  # Theme settings
  defaultTheme = 'auto' # auto, dark, light
  disableThemeToggle = false
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = true

  # Social Icons
  [[params.socialIcons]]
    name = 'github'
    url = 'https://github.com/gui13go'

  [[params.socialIcons]]
    name = 'substack'
    url = 'https://guilhermeviegas.substack.com'

  # Cover image settings
  [params.cover]
    hidden = false
    hiddenInList = false
    hiddenInSingle = false

  # Fast Search
  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1_000
    threshold = 0.4
    minMatchCharLength = 0
    keys = ['title', 'permalink', 'summary', 'content']

  mainSections = ['blogs']

# Main Menu
[menu]
  [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about/'
    weight = 10

  [[menu.main]]
    identifier = 'blogs'
    name = 'Blogs'
    url = '/blogs/'
    weight = 20

  [[menu.main]]
    identifier = 'publications'
    name = 'Publications'
    url = '/publications/'
    weight = 30

  [[menu.main]]
    identifier = 'geolayers'
    name = 'GeoLayers'
    url = '/geolayers/'
    weight = 40

  [[menu.main]]
    identifier = 'gallery'
    name = 'Gallery'
    url = '/gallery/'
    weight = 50

  [[menu.main]]
    identifier = 'tools'
    name = 'Tools'
    url = '/tools/'
    weight = 60

  [[menu.main]]
    identifier = 'search'
    name = 'Search'
    url = '/search/'
    weight = 70

[outputs]
  home = ['HTML', 'RSS', 'JSON']

[taxonomies]
  category = 'categories'
  tag = 'tags'

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    style = 'dracula'
  [markup.goldmark.renderer]
    unsafe = true

[module]
  [[module.mounts]]
    source = 'static'
    target = 'static'

  [[module.mounts]]
    source = 'assets/images'
    target = 'static/images'
